config/routes.rb
Fora::Application.routes.draw do
  root 'topics#index'

  delete 'sign_out' => 'sessions#destroy', as: :sign_out

  match 'auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  match 'auth/failure' => 'sessions#failure', via: :get

  get 'go/:key'  => 'nodes#show', as: :node
  get 'new/:key' => 'topics#new', as: :new_topic

  post 'like/:type/:id' => 'likes#create_or_destroy',     as: :like
  post 'bookmark/:id'   => 'bookmarks#create_or_destroy', as: :bookmark
  get  'bookmarks'      => 'bookmarks#index',             as: :bookmarks

  resources :users, only: [:new, :create]

  resources :nodes, only: [:index, :new, :create]

  resources :topics, except: [:edit, :update, :destroy, :new] do
    resources :replies, only: [:create, :index]
  end

  resources :notifications, only: [:index, :destroy] do
    delete 'clear', on: :collection
  end

  namespace :admin do
    resources :nodes,   only: :create
    resources :topics,  only: :destroy
    resources :replies, only: :destroy
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  include Redis::Objects
  include Mentionable
  include Likeable

  default_scope -> { order('updated_at DESC') }

  belongs_to :user, counter_cache: true
  belongs_to :node, counter_cache: true, touch: true

  has_many :replies, dependent: :destroy

  counter :hits

  validates :title, presence: true,
                    length: { maximum: 100 }

  validates :user_id, presence: true
  validates :node_id, presence: true

  delegate :username, to: :user

  self.per_page = 20

  def new_reply(replier, reply_params)
    replies.build(reply_params).tap do |reply|
      reply.user_id = replier.id
      update(last_replier_username: replier.username) if reply.save
    end
  end

  private

  def mention_scan_text
    "#{title} #{body}"
  end
end

# == Schema Information
#
# Table name: topics
#
#  id                    :integer          not null, primary key
#  title                 :string(255)      not null
#  body                  :text
#  likes_count           :integer          default(0)
#  replies_count         :integer          default(0)
#  last_replier_username :string(255)
#  user_id               :integer
#  node_id               :integer
#  created_at            :datetime
#  updated_at            :datetime
#
# Indexes
#
#  index_topics_on_node_id  (node_id)
#  index_topics_on_user_id  (user_id)
#

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < Admin::AdminController
  include TopicsConcern

  def destroy
    redirect_to root_url, notice: 'Delete topic successfully' if @topic.destroy
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  include TopicsConcern

  before_filter :require_login, except: [:index, :show]
  after_filter  :update_hits, only: :show

  def index
    @topics = Topic.page(params[:page]).includes(:node, :user)
  end

  def show
    @replies = @topic.replies.includes(:user, :like_users)
  end

  def new
    @node = Node.find_by key: params[:key]
    @node || redirect_to(root_path, alert: I18n.t('node_missing')) && return

    if @node.approved?
      @topic = @node.topics.new
    else
      redirect_to root_url, alert: I18n.t('node_not_approved')
    end
  end

  def create
    @topic = current_user.topics.build(topic_params)

    if @topic.save
      redirect_to @topic
    else
      render 'new'
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :body, :node_id)
  end

  def update_hits
    @topic.hits.incr
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def topic_title_tag(topic, reply_id = nil)
    return unless topic
    anchor = reply_id && "reply-#{reply_id}"
    link_to topic.title, topic_path(topic, anchor: anchor)
  end
end

app/views/topics/_topic.html.slim
li.topic-item.media
  = avatar_tag topic.user
  = node_tag topic.node
  .media__body
    = link_to topic.title, topic, class: 'delta'
    ul.topic__meta.zeta.nav.fade
      li.meta-item = username_tag topic.username
      li.meta-item = link_to "#{topic.replies_count} replies", "#{topic_path(topic)}#replies"
      li.meta-item = timeago topic.updated_at
      - if topic.last_replier_username
        li.meta-item
          ' last reply from
          = username_tag topic.last_replier_username

app/views/topics/_topic_footer.html.slim
.topic__footer.delta.text--right.soft-half.hard--top
  - if current_user
    = link_to like_path(@topic.class, @topic.id), method: :post,
    class: 'js-like', remote: true do
      = icon @topic.liked_by?(current_user) ? 'heart' : 'heart-empty'

    = link_to bookmark_path(@topic.id), method: :post,
    id: 'js-bookmark', remote: true do
      = icon current_user.bookmarked?(@topic.id) ? 'bookmark' : 'bookmark-empty'

  = link_to icon('twitter'), nil, class: 'js-share',
  data: { network: 'twitter', text_selector: '.topic__title' }
  = link_to icon('weibo'), nil, class: 'js-share',
  data: { network: 'weibo', text_selector: '.topic__title' }

  - if current_user.try(:admin?)
    = link_to icon('trash'), [:admin, @topic], method: :delete,
        id: 'js-delete-topic', data: { confirm: t('are_you_sure') }

app/views/topics/_topic_meta.html.slim
ul.topic__meta.zeta.fade.nav
  li.meta-item By #{username_tag topic.username}
  li.meta-item = timeago(topic.created_at)
  li.meta-item
    = icon('heart')
    span.topic__likes.js-likes-count data-count=topic.likes_count Likes
  li.meta-item #{topic.hits} hits
  li.meta-item = link_to "#{topic.replies_count} replies", '#replies'

app/views/topics/index.html.slim
ul.topics.card.block-list
  = render @topics
  = will_paginate @topics, page_links: false

- content_for :sidebar do
  = render @topics.map(&:node).uniq.take(3)

app/views/topics/new.html.slim
- @node ||= @topic.node

.card
  .card__header
    = breadcrumbs link_to(@node.name, @node), t('new_topic')

  .islet.flush
    = simple_form_for @topic do |f|
      = f.input :title, label: false, input_html: { class: 'input--block' }
      = f.input :body,  label: false, input_html: { rows: 18 }
      = f.input :node_id, as: :hidden
      = f.button :submit, class: 'btn--primary float--right'

- content_for :sidebar do
  = render @node

app/views/topics/show.html.slim
= div_for @topic, class: 'card' do
  .card__header.media
    = avatar_tag @topic.user
    = node_tag @topic.node
    .media__body
      h1.topic__title.gamma.flush = @topic.title
      = render partial: 'topic_meta', locals: { topic: @topic }

  .topic__body.body-text.islet.flush.hard--bottom.js-autohtml
    = @topic.body

  = render partial: 'topic_footer'

- if @replies.any?
  ol.replies.card.block-list#replies = render @replies

= render 'replies/form'

- content_for :sidebar do
  = render @topic.node