config/routes.rb
Fora::Application.routes.draw do
  root 'topics#index'

  delete 'sign_out' => 'sessions#destroy', as: :sign_out

  match 'auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  match 'auth/failure' => 'sessions#failure', via: :get

  get 'go/:key'  => 'nodes#show', as: :node
  get 'new/:key' => 'topics#new', as: :new_topic

  post 'like/:type/:id' => 'likes#create_or_destroy',     as: :like
  post 'bookmark/:id'   => 'bookmarks#create_or_destroy', as: :bookmark
  get  'bookmarks'      => 'bookmarks#index',             as: :bookmarks

  resources :users, only: [:new, :create]

  resources :nodes, only: [:index, :new, :create]

  resources :topics, except: [:edit, :update, :destroy, :new] do
    resources :replies, only: [:create, :index]
  end

  resources :notifications, only: [:index, :destroy] do
    delete 'clear', on: :collection
  end

  namespace :admin do
    resources :nodes,   only: :create
    resources :topics,  only: :destroy
    resources :replies, only: :destroy
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base

  default_scope -> { order('updated_at DESC') }
  scope :unread, -> { where(is_read: false) }

  belongs_to :source, class_name: 'User'
  belongs_to :target, class_name: 'User'
  belongs_to :topic
  belongs_to :reply

  validates_presence_of :source_id, :target_id, :topic_id, :kind

  delegate :username, to: :source, prefix: true

  def body
    reply.try(:body) || topic.try(:body)
  end
end

# == Schema Information
#
# Table name: notifications
#
#  id         :integer          not null, primary key
#  target_id  :integer
#  source_id  :integer
#  topic_id   :integer
#  reply_id   :integer
#  like_id    :integer
#  is_read    :boolean          default(FALSE)
#  kind       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#
# Indexes
#
#  index_notifications_on_is_read    (is_read)
#  index_notifications_on_like_id    (like_id)
#  index_notifications_on_reply_id   (reply_id)
#  index_notifications_on_source_id  (source_id)
#  index_notifications_on_target_id  (target_id)
#  index_notifications_on_topic_id   (topic_id)
#

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :require_login

  def index
    @notifications = current_user.notifications
      .includes(:source, :topic, :reply).page(params[:page])
    current_user.read_notifications
  end

  def destroy
    @notification = current_user.notifications.find(params[:id])
    @notification.destroy if @notification

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def clear
    current_user.clear_notifications

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end
end

app/views/notifications/_notification.html.slim
= content_tag_for :li, notification, class: 'media zeta' do
  = avatar_tag notification.source
  .media__body
    .notification__title.fade
      = timeago(notification.created_at, class: 'js-timeago float--right')
      = username_tag(notification.source_username)
      = t("notification_types.#{notification.kind}")
      = topic_title_tag notification.topic, notification.reply_id

    - if notification.body.present?
      .notification__body.soft-half.body-text.js-autohtml
        = notification.body

  = link_to icon('close'), notification_path(notification), remote: true,
      method: :delete, class: 'show-on-hover notification__delete-icon js-delete-notification'

app/views/notifications/clear.js.erb
$('.notification').hide('slow');

app/views/notifications/destroy.js.erb
$('#<%= dom_id @notification %>').hide('slow');

app/views/notifications/index.html.slim
ol.notifications.card.block-list
  .card__header
    = link_to clear_notifications_path, method: :delete,
    id: 'js-clear-notification', remote: true,
        class: 'btn btn--small btn--inverse float--right' do
      = icon('trash')
      = t('clear')
    = breadcrumbs t('notifications')

  = render @notifications