config/routes.rb
Fora::Application.routes.draw do
  root 'topics#index'

  delete 'sign_out' => 'sessions#destroy', as: :sign_out

  match 'auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  match 'auth/failure' => 'sessions#failure', via: :get

  get 'go/:key'  => 'nodes#show', as: :node
  get 'new/:key' => 'topics#new', as: :new_topic

  post 'like/:type/:id' => 'likes#create_or_destroy',     as: :like
  post 'bookmark/:id'   => 'bookmarks#create_or_destroy', as: :bookmark
  get  'bookmarks'      => 'bookmarks#index',             as: :bookmarks

  resources :users, only: [:new, :create]

  resources :nodes, only: [:index, :new, :create]

  resources :topics, except: [:edit, :update, :destroy, :new] do
    resources :replies, only: [:create, :index]
  end

  resources :notifications, only: [:index, :destroy] do
    delete 'clear', on: :collection
  end

  namespace :admin do
    resources :nodes,   only: :create
    resources :topics,  only: :destroy
    resources :replies, only: :destroy
  end
end

app/views/shared/_flashes.html.slim
- flash.each do |type, message|
  - next if message.blank?
  div class="flash flash--#{type}"
    span = message

app/views/shared/_header.html.slim
nav.site-nav
  .container
    ul.nav.main-nav
      li = link_to t('site.name'), root_path, class: 'logo'
      li = nav_link 'topics', topics_path
      li = nav_link 'nodes',  nodes_path
      ul.nav.float--right.flush
        - if current_user
          li = link_to icon('trash'), notifications_path,
            class: 'notifier', title: t('notifications'),
              data: { count: current_user.unread_notifications_count }
          li.dropdown
            = avatar_tag current_user, :thumb
            = icon 'down-dir'
            ul.dropdown-list
              li = link_to t('notifications'), notifications_path
              li = link_to t('bookmarks'), bookmarks_path
              li = link_to t('sign_out'), sign_out_path, method: :delete
        - else
          li = link_to icon('twitter icon--circular'),
            '/auth/twitter', title: t('twitter_sign_in')
          li = link_to icon('weibo icon--circular'),
            '/auth/weibo', title: t('weibo_sign_in')