config/routes.rb
Fora::Application.routes.draw do
  root 'topics#index'

  delete 'sign_out' => 'sessions#destroy', as: :sign_out

  match 'auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  match 'auth/failure' => 'sessions#failure', via: :get

  get 'go/:key'  => 'nodes#show', as: :node
  get 'new/:key' => 'topics#new', as: :new_topic

  post 'like/:type/:id' => 'likes#create_or_destroy',     as: :like
  post 'bookmark/:id'   => 'bookmarks#create_or_destroy', as: :bookmark
  get  'bookmarks'      => 'bookmarks#index',             as: :bookmarks

  resources :users, only: [:new, :create]

  resources :nodes, only: [:index, :new, :create]

  resources :topics, except: [:edit, :update, :destroy, :new] do
    resources :replies, only: [:create, :index]
  end

  resources :notifications, only: [:index, :destroy] do
    delete 'clear', on: :collection
  end

  namespace :admin do
    resources :nodes,   only: :create
    resources :topics,  only: :destroy
    resources :replies, only: :destroy
  end
end

app/views/layouts/_hottest_bar.html.slim
#hottest.container-box
  .header
    span.muted = "hottest topics today"
  ul
    - @hottest.each do |item|
      li.hottest-item
        .row.ml0
          .span2 = avatar_tag(item.user, name: false, size: :thumb)
          .span10
            small = link_to item.title, topic_path(item)
  .footer

app/views/layouts/application.html.slim
doctype html
html
  head
    title = t('site.name')
    = stylesheet_link_tag    'application', 'data-turbolinks-track' => true, media: 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body class=body_class
    = render 'shared/header'

    .container
      - if @custom_layout
        = yield
      - else
        .grid
          .main.grid__item.one-whole.desk-two-thirds
            = render 'shared/flashes'
            = yield
          .sidebar.grid__item.one-whole.desk-one-third
            = yield :sidebar